# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1b02dd7fe629896c28bff027c9981946"
name = "Dev Quyen Deep Search"
handle = "dev-quyen-deep-search"
application_url = "https://sell-federal-pre-insertion.trycloudflare.com"
embedded = true

[tunnel]
provider = "cloudflare"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,read_orders,write_orders"
use_legacy_install_flow = false

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-07"

[auth]
redirect_urls = [
  "https://sell-federal-pre-insertion.trycloudflare.com/auth/callback",
  "https://sell-federal-pre-insertion.trycloudflare.com/auth/shopify/callback",
  "https://sell-federal-pre-insertion.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
