# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1b02dd7fe629896c28bff027c9981946"
name = "Dev Quyen Deep Search"
handle = "dev-quyen-deep-search"
application_url = "https://61f33a41bed2.ngrok-free.app"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products"
use_legacy_install_flow = false

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[auth]
redirect_urls = [
  "https://61f33a41bed2.ngrok-free.app/auth/callback",
  "https://61f33a41bed2.ngrok-free.app/auth/shopify/callback",
  "https://61f33a41bed2.ngrok-free.app/api/auth/callback"
]

[pos]
embedded = false
